### ISSUE TITLE
Context file/URL

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vc-status-list-2021#10]
Examples reference URL https://w3id.org/vc-status-list-2021/v1 in `@context`:
https://github.com/w3c-ccg/vc-status-list-2021/blob/7d8f66b06483a22edfdfcd99bad86c7a56867145/index.html#L308
But that URL resolves to a 404.

Revocation List 2020 used a similar URL: https://w3id.org/vc-revocation-list-2020/v1, which resolves successfully.

There is a context file in this repo currently, but it is for 2020:
https://github.com/w3c-ccg/vc-status-list-2021/blob/7d8f66b06483a22edfdfcd99bad86c7a56867145/contexts/vc-revocation-list-2020/v1.jsonld

Should the 2020 context file in this repo be updated and renamed for 2021, and a similar namespace requested in w3id.org?

**Comment by lemoustachiste** [comment]
+1, was about to open similar issue

**Comment by clehner** [comment]
The context file was updated in #15 and is now at https://w3id.org/vc/status-list/v1 (https://w3c-ccg.github.io/vc-status-list-2021/contexts/v1.jsonld). The namespace was obtained in https://github.com/perma-id/w3id.org/pull/2489. Thanks @JSAssassin.

**Comment by nikosft** [comment]
This issue has not been fixed. In most (all?) examples https://w3id.org/vc-status-list-2021/v1 is used as context which resolves to a 404

**Comment by clehner** [comment]
@nikosft indeed I missed that; the w3id.org URL that was set up was different from what was in the examples. I wonder if it was intended for the w3id.org URL to have the suite year. Anyway, #22 is open to use the w3id.org URL that was registered for this suite's current context file.

**Comment by msporny** [comment]
I believe that all examples in the spec have been updated to use https://w3id.org/vc/status-list/2021/v1 now, which resolves.
