### ISSUE TITLE
Need clarification on compression algorithm & container used

### ISSUE THREAD

**Issue by thehenrytsai** [w3c-ccg/vc-status-list-2021#13]
The current phrasing on compression is "ZLIB compression algorithm [RFC1950]", however upon reading the RFC it looks like ZLIB is a container format and the actual "default" compression algorithm is called `deflate`.

One would interpret the spec as: use `deflate` algorithm and `ZLIB` as the container.

However, the [example](https://w3c-ccg.github.io/vc-status-list-2021/#example-example-revocationlist2021-credential) given in the spec  uses `GZIP` as the container (specifically the string `H4sIAAAAAAAAA-3BMQEAAADCoPVPbQsvoAAAAAAAAAAAAAAAAP4GcwM92tQwAAA`).

So we are seeking clarification so that we can produce an interoperable implementation.

**Comment by clehner** [comment]
The text has been updated in #15 to say GZIP. The example was also changed, but seems to still be GZIP:
https://github.com/w3c-ccg/vc-status-list-2021/blob/29b21adf424ff56e4005879953c010339dc6a681/index.html#L475

**Comment by thehenrytsai** [comment]
Thank you. I think the language is still not precise as GZIP is a container not the actual compression algorithm. But I understand the requirement now so will close.
