### ISSUE TITLE
Add status list type field

### ISSUE THREAD

**Issue by csuwildcat** [w3c-ccg/vc-status-list-2021#2]
Would it be possible to add a field to note the type of status a status list is for? Like for example: `listType: "revocation"`, where you could put 'suspended', 'pending', or any other status list intent someone wanted?

**Comment by bumblefudge** [comment]
On today's VC-EDU call, some other list types were discussed: "endorsed" or "certified" or "notarized" might be other lists worth exploring for other use cases...

**Comment by bumblefudge** [comment]
[This issue](https://github.com/w3c/vc-data-model/issues/820) over on the VC data model repo also wonders if "refreshed" is a status worth defining (whether in a list type or otherwise)

**Comment by msporny** [comment]
This has been implemented in the latest specification:

```
    "statusPurpose": "revocation | suspension | anyOtherTextStringYouCanImagine"
```

More here: https://w3c-ccg.github.io/vc-status-list-2021/#statuslist2021entry
