### ISSUE TITLE
StatusList2021Credential or RevovationList2021 Credential

### ISSUE THREAD

**Issue by paulfdietrich** [w3c-ccg/vc-status-list-2021#26]
Section 2.3 titled StatusList2021Credential includes a credential example which is a RevocationList2021 Credential of type "RevocationList2021"

originally I though this was typo and all of these should have said StatusList2021 since they could be revocation lists or suspensions lists but as I went into to make a PR (I'm new to this group) I realized that this language might be evolving and I don't know which direction its going.

**Comment by msporny** [comment]
Fixed in 15ee3c63555c049ce23485956be7a9544ac7edab.
