### ISSUE TITLE
Are suppension and revocation mutially exclusive?

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/vc-status-list-2021#33]
The spec provides an example for a [Status List 2021 Entry](https://w3c-ccg.github.io/vc-status-list-2021/#statuslist2021entry)

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  "id": "https://example.com/credentials/23894672394",
  "type": ["VerifiableCredential"],
  "issuer": "did:example:12345",
  "issued": "2021-04-05T14:27:42Z",
  "credentialStatus": {
    "id": "https://example.com/credentials/status/3#94567"
    "type": "StatusList2021Entry",
    "statusPurpose": "revocation",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  },
  "credentialSubject": {
    "id": "did:example:6789",
    "type": "Person"
  },
  "proof": { ... }
}
```

Here the `statusPurpose` is defined as a string value with the options of `revocation` or `suspension` followed by a single index which is provided as `94567`. 

Does this mean that `revocation` and `suspension` are mutually exclusive. To include them both in the same status list, I need to have two bits for revoked yes, or no, and suspended yes or no.

00 Valid 
01 Suspended
10 Revoked
11 (likely) Suspended then revoked

First i would like some clarity on the issue. Is it the intention of the spec to make suspension and revocation mutually exclusive? Such as when the credential is issued, the issuer understands the option that they can either issue a `suspend-able` credential that can be toggled on or off at will, OR a `revocable` credential, where revoking a credential a single time will render it invalid. OR is it the intention of the spec to allow these two statuses to be applied to the same credential?

**Comment by dlongley** [comment]
The intention of the spec is for there to be one status purpose per list. A VC can be associated with as many different status lists as desired. So, for example, a VC could be associated with both a revocation list and with a suspension list, having a current status in both lists. So the answer is "yes" to your last question, the intention of the spec is to allow these two statuses (or N-many statuses) to be applied to the same credential.

**Comment by BenjaminMoe** [comment]
> The answer is "yes" to your last question, the intention of the spec is to allow these two statuses (or N-many statuses) to be applied to the same credential.

Thanks for the reply @dlongley. Is the intended implementation for this to have `credentialStatus` be an object or an array of array of objects? Or is this a different intended JSON representation of a credential with both a revocation and suspension index?

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  "id": "https://example.com/credentials/23894672394",
  "type": ["VerifiableCredential"],
  "issuer": "did:example:12345",
  "issued": "2021-04-05T14:27:42Z",
  "credentialStatus": [
   {
    "id": "https://example.com/credentials/status/3#94567"
    "type": "StatusList2021Entry",
    "statusPurpose": "revocation",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  },
  {
    "id": "https://example.com/credentials/status/4#94567"
    "type": "StatusList2021Entry",
    "statusPurpose": "suspension",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/4"
  }
  ],
  "credentialSubject": {
    "id": "did:example:6789",
    "type": "Person"
  },
  "proof": { ... }
}
```

**Comment by dlongley** [comment]
@BenjaminMoe,

Yes, `credentialStatus` can be either an object or an array of objects -- and you'd represent two different lists just like in your example (which I pasted here below and showed with a different index for suspension just to highlight that they needn't be the same index -- but could be -- in each list):

```js
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  "id": "https://example.com/credentials/23894672394",
  "type": ["VerifiableCredential"],
  "issuer": "did:example:12345",
  "issued": "2021-04-05T14:27:42Z",
  "credentialStatus": [
   {
    "id": "https://example.com/credentials/status/3#94567"
    "type": "StatusList2021Entry",
    "statusPurpose": "revocation",
    "statusListIndex": "94567",
    "statusListCredential": "https://example.com/credentials/status/3"
  },
  {
    "id": "https://example.com/credentials/status/4#23452"
    "type": "StatusList2021Entry",
    "statusPurpose": "suspension",
    "statusListIndex": "23452",
    "statusListCredential": "https://example.com/credentials/status/4"
  }
  ],
  "credentialSubject": {
    "id": "did:example:6789",
    "type": "Person"
  },
  "proof": { ... }
}
```

**Comment by BenjaminMoe** [comment]
@dlongley Thanks for following up on the issue!
